# Generated by Django 3.1.2 on 2020-11-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20201126_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sr_no',
            field=models.IntegerField(default=0),
        ),
    ]
