# Generated by Django 3.1.2 on 2020-12-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20201127_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lable',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale')], max_length=15, null=True),
        ),
    ]
