# Generated by Django 3.1.2 on 2020-12-08 09:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201201_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cart.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Bridal', 'Bridal'), ('Casual', 'Casual'), ('Festive', 'Festive'), ('Party', 'Party'), ('Wedding', 'Wedding')], default='', max_length=10, null=True),
        ),
    ]
