# Generated by Django 3.1.2 on 2020-12-08 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_auto_20201208_1430'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
