# Generated by Django 3.1.2 on 2020-12-10 07:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20201210_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(default='', max_length=50)),
                ('txn_id', models.CharField(default='', max_length=50)),
                ('payer_id', models.CharField(default='', max_length=50)),
                ('mode', models.CharField(default='', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
            ],
        ),
    ]
