# Generated by Django 3.1.2 on 2020-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
