# Generated by Django 3.1.2 on 2021-06-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='txn_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cart.payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
