# Generated by Django 3.1.2 on 2021-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_auto_20210602_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancel_order',
            name='refund_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
