# Generated by Django 3.1.2 on 2021-06-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cancel_order_refund_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancel_order',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orders'),
        ),
    ]
